### PR TITLE
Throwing together a new site for feedback

### PR DESCRIPTION
**Pull request by JakeGinnivan**
Uses one of the html5up templates, downside is it doesn't seem responsive though. 

Let me know what you guys think @robdmoore @MehdiK @mwhelan 

Want to do new landing pages for each of the projects too, kill docs.teststack.net and simply use the github wiki for docs.

### CODE REVIEW

**Comment by ByteBlast** [comment]
I really like your template, @mwhelan.

I noticed this topic has come to a standstill. Can I be of help? I will gladly dedicate some time to help you bring either of these templates to the public.

**Comment by JakeGinnivan** [comment]
hey @ByteBlast 

Any help is appreciated. I think @mwhelan's branch needs to be pulled down. Reviewed/text updated if needed then pushed to the gh-pages branch. Just getting it online will be a great start, then we can iterate. It shouldn't take long to get it all running.

I am around today so if you put the PR up I can merge it and help out if needed

**Comment by mwhelan** [comment]
Yes, that would be awesome @ByteBlast . The branch is here:
https://github.com/mwhelan/Thinkful_LandingPage

I'm not that good with front-end stuff and put it together as part of a course I took. My point being, feel free to enhance things that can be done better. Let me know if I can help too. Perhaps loop me and Jake in by email. You can get me on mjmwdev at gmail.com.

**Comment by JakeGinnivan** [comment]
jake at ginnivan dot net is my email

**Pull request closed without merging**
