### PR TITLE
Bought in Michael's template

### PR DESCRIPTION
**Pull request by AlexArchive**
I bought in @mwhelan's template and then removed the now-initule files. 

There are still some small tweaks that need applying. I will document my thoughts here for the time being. 

**Implementation**
- I think we should use a CDN when possible.
- I think we should include a Html5 shiv for older browsers.
- I think we should show a warning to users with incompatible (read: old) browsers.
- Maybe we should use use a static site generator like Jekyll. Thoughts?

**Aesthetics**

Awesome job @mwhelan. The page you made looks _superb_. I have just a few thoughts: 
- I think the navigation alternative color is too insipid -- it's hard to see.
- I think you're using the [Dribble logo](https://d13yacurqjgara.cloudfront.net/assets/dribbble-ball-dnld-2bd6a8870d1da1288282916f7b91e39e.png) for the link icons. I suppose we should change this to something more appropriate? 
- There a couple of minor layout issues when viewing the page on a small device. See [exhibit A](http://i.imgur.com/LzVOSAw.png) and [exhibit B](http://i.imgur.com/LzVOSAw.png).

**Content**

I read your [discussion](https://github.com/TestStack/teststack.github.com/pull/9) about where you to take this website in terms of content. I am not entirely sure about what it is you decided on. Could someone please clarify? 

Some thoughts of my own about content: 
- Maybe we should include @jason-roberts [new course](http://www.pluralsight.com/courses/automated-aspdotnet-mvc) in the Pluralsight box.
- I think we should make it immediately clear that the website itself and all the encompassed projects are open-source. I think open-source is a big part of TestStack.

### CODE REVIEW

**Comment by ByteBlast** [comment]
I'm eager to make all of these changes by the way.

I just want to make sure I'm on the right track :smile: .

**Comment by mwhelan** [comment]
Great stuff @ByteBlast . I would say go ahead with all your suggestions on Implementation and Aesthetics and your suggestions for Content. With regards to a static site generator I would recommend [Sandra.Snow](https://github.com/Sandra/Sandra.Snow) which has the advantage of being .Net based. Others might have other suggestions.

**Comment by JakeGinnivan** [comment]
If we stick we Jekyll we can use GitHub pages out of the box for hosting. Sandra.Snow will require us to have the build externally and push updates etc.

**Comment by ByteBlast** [comment]
@JakeGinnivan My thoughts exactly.

**Comment by mwhelan** [comment]
Yup, good point. That makes more sense. 

I would be keen to include the blog too if we can. I've recently been looking at some of the cool TestStack related blog posts you guys have done and I would love to see some of it copied there as it would be a fantastic central resource.

**Comment by ByteBlast** [comment]
I think I can quite easily add a blog because

- [I use Bootstrap to theme my blog engine](https://github.com/ByteBlast/Medium) and
- because [I use Jekyll for my personal blog.](https://github.com/ByteBlast/byteblast.github.io)

I think we should tackle this another day in a different pull request though?

I'll make all of those aforementioned changes this evening. 

Please let me know if you want me to accommodate any additional content. I'm not in a huge rush personally. You should feel free to take time to deliberate with @robdmoore  and @MehdiK you want to.

**Comment by mwhelan** [comment]
Yeah, totally. I was just mentioning it to guage feedback and to have in the back of your mind.

**Comment by JakeGinnivan** [comment]
Yep, lets tackle as a new PR. Also content updates can be done separately.

If we get the site updated then we can all chip in small things when we have a chance.

**Comment by ByteBlast** [comment]
Sounds good lads.

**Comment by ByteBlast** [comment]
All done I think.

**Comment by robdmoore** [comment]
LYW

**Comment by MehdiK** [comment]
Awesome work @ByteBlast and I like all your suggestions.

**Comment by JakeGinnivan** [comment]
Looks great. 

I am all for sass, unsure if we go jekyll if we need a grunt build but happy to chat about any suggestions.

**Comment by JakeGinnivan** [comment]
I have just updated the IP address for this site. I had the domain pointed at the outdated IP addresses. Had it on my todo for this week anyways.

Will take a while for DNS propagation to happen, then I will try to get the site to update. At the moment they are failing the build due to the old ip address usage.

I will post once it is all up and running

**Comment by ByteBlast** [comment]
Awesome. Thanks all.

**Comment by mwhelan** [comment]
Awesome stuff! Thanks @ByteBlast and @JakeGinnivan

**Comment by JakeGinnivan** [comment]
Boom http://teststack.net

Thanks @mwhelan for the initial template and @ByteBlast for making this happen.

**Comment by robdmoore** [comment]
:dancer: :balloon: 

favicon needs to be updated btw

**Comment by mwhelan** [comment]
Yeah, would be good to capture first impressions of things that jump out that need to be changed, content or otherwise.

**Pull request merged**
